### ISSUE TITLE
ModuleNotFoundError in `process_executor.py`

### ISSUE THREAD

**Issue by ancarnevali** [kadkhodaei-research-group/XIE-SPP#1]
Hi!
I am trying to run the Synthesisability predictor version 2 from the provided `example_synthesizability` notebook, but am encountering an issue.
```
from xiespp import synthesizability, get_test_samples
# or 
# from xiespp import synthesizability_2 as synthesizability, get_test_samples ### using this import line results in the same error
samples = get_test_samples('GaN')
model = synthesizability.SynthesizabilityPredictor()
```
no problems until here, but `model.predict(samples)` returns:
```
Reading CIF files...

100%|██████████| 3/3 [00:00<00:00, 52.63it/s]

Preparing image objects...
Checking image requirements...


100%|██████████| 3/3 [00:00<00:00, 52.15it/s]

---------------------------------------------------------------------------

_RemoteTraceback                          Traceback (most recent call last)

_RemoteTraceback: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py", line 426, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'xiespp'


```
which in turn causes:

```
The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)

[<ipython-input-10-8167be16a727>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.predict(samples)

12 frames

[/content/XIE-SPP/xiespp/CVR/keras_tools.py](https://localhost:8080/#) in predict(self, generator, include_invalid_samples, return_all_ensembles, verbose, input_format, **kwargs)
    123         :param kwargs: The rest of Keras predict parameters
    124         """
--> 125         generator = prepare_data(
    126             generator,
    127             image_params=self.image_params,

[/content/XIE-SPP/xiespp/CVR/keras_tools.py](https://localhost:8080/#) in prepare_data(data_input, image_params, input_format, verbose)
     83             verbose=verbose,
     84         )
---> 85         data_input.data_preparation()
     86     return data_input
     87 

[/content/XIE-SPP/xiespp/CVR/generator.py](https://localhost:8080/#) in data_preparation(self, verbose)
    201         # self.prepare_point_clouds()
    202         self.image_processor.verbose = verbose or self.image_processor.verbose
--> 203         self.image_processor.prepare_point_clouds()
    204         self.set_index()
    205 

[/content/XIE-SPP/xiespp/CVR/image_processor.py](https://localhost:8080/#) in prepare_point_clouds(self, check_requirements)
     73     def prepare_point_clouds(self, check_requirements=True):
     74         if 'image' not in self.df.columns:
---> 75             self.image_preparation(check_requirements=check_requirements)
     76         # df = self.df.loc[self.index]
     77         df = self.df[self.df['is_valid']]

[/content/XIE-SPP/xiespp/CVR/image_processor.py](https://localhost:8080/#) in image_preparation(self, input_col, check_requirements)
     53 
     54         if check_requirements:
---> 55             self.check_image_requirements()
     56 
     57     def check_image_requirements(self):

[/content/XIE-SPP/xiespp/CVR/image_processor.py](https://localhost:8080/#) in check_image_requirements(self)
     61         if self.verbose:
     62             print('Checking image requirements...', flush=True)
---> 63         df.loc[df.index, 'is_valid'] = utg.parallel_apply(
     64             df.loc[:, 'image'], lambda x: x.check_requirements(),
     65             progres_bar=self.verbose,

[/content/XIE-SPP/xiespp/CVR/util_cvr.py](https://localhost:8080/#) in parallel_apply(func, n_jobs, ignor_warnings, progres_bar, parallel, mute_printing, *args, **kwargs)
    149                 return [func(*it, **kwargs) for it in iterator]
    150 
--> 151             output = Parallel(
    152                 n_jobs=n_jobs,
    153                 # prefer='threads' if n_jobs == 1 else 'processes',

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in __call__(self, iterable)
   2005         next(output)
   2006 
-> 2007         return output if self.return_generator else list(output)
   2008 
   2009     def __repr__(self):

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _get_outputs(self, iterator, pre_dispatch)
   1648 
   1649             with self._backend.retrieval_context():
-> 1650                 yield from self._retrieve()
   1651 
   1652         except GeneratorExit:

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _retrieve(self)
   1752             # worker traceback.
   1753             if self._aborting:
-> 1754                 self._raise_error_fast()
   1755                 break
   1756 

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _raise_error_fast(self)
   1787         # called directly or if the generator is gc'ed.
   1788         if error_job is not None:
-> 1789             error_job.get_result(self.timeout)
   1790 
   1791     def _warn_exit_early(self):

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in get_result(self, timeout)
    743             # callback thread, and is stored internally. It's just waiting to
    744             # be returned.
--> 745             return self._return_or_raise()
    746 
    747         # For other backends, the main thread needs to run the retrieval step.

[/usr/local/lib/python3.10/dist-packages/joblib/parallel.py](https://localhost:8080/#) in _return_or_raise(self)
    761         try:
    762             if self.status == TASK_ERROR:
--> 763                 raise self._result
    764             return self._result
    765         finally:

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

Can you see what the issue is here, and how to solve it? Running the model in Version 1 from the same notebook works (although after commenting out the `use_multiprocessing`, `workers`, `max_queue_size` arguments of the `.predict` method).

Thank you!

**Comment by adavaria** [comment]
Thank you for bringing this to our attention. The issue is fixed, and I have also made the installation easier.
